trigger:
- main # main branch を使用

name: Deploy Bicep files

variables:
  poolName: 'tak-test-agentpool' # 今回Self-Hosted agent なので、設定したエージェントプール名を入力＆poolNameへ変数名を変更
 
  azureServiceConnection: 'tak-test-ARM' # sevice connectionの名前を入力
  resourceGroupName: 'tak-test-bicep' # 対象のRG名を入力
  location: 'japaneast' # 対象のlocationを指定
  templateFile: './storageaccount.bicep' #　対象のbicepファイルを指定
  templateParameterFile: './storageaccount.parameters.json' # parameter file 追加
pool:
  name: $(poolName) # ↑の変数名変更に合わせて変更

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    useGlobalConfig: false
    inlineScript: |
      az --version
      az group create --name $(resourceGroupName) --location $(location)
      az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile) --parameters $(templateParameterFile) # paramters を追加
